algoritmo "semnome"
// Função :
// Autor :
// Data : 16/08/2022
// Seção de Declarações 
var
time:caracter
inicio
escreval("Digite um time: ")
leia(time)

escolha time
        caso "São paulo","Santos","Palmeiras","Corinthians"
             escreval("Eixo SP")
        caso "Flamengo","Fluminense","BotaFogo","Vasco"
             escreval("Eixo RJ")
        outrocaso
             escreval("Não sei da onde é")
fimescolha




fimalgoritmo
