algoritmo "semnome"
// Função :
// Autor :
// Data : 09/05/2022
// Seção de Declarações 
var
valor_peca:real
qntd_vendida:real
comissao:real
inicio
// Dados de Entrada
escreval("digite o valor da peça")
leia(valor_peca)
escreval("digite o quantidade vendida")
leia(qntd_vendida)
// processamento
comissao<-(valor_peca*qntd_vendida)*0.05
// Dados de Saída
escreval("a sua comissão é: ",comissao)

fimalgoritmo
