algoritmo "semnome"
// Função :
// Autor :
// Data : 18/09/2022
// Seção de Declarações 
var
n1, n2, alunos: inteiro
media: real

inicio
para alunos de 1 ate 10 faca
     escreval("Digite a primeira nota:")
     leia(n1)
     escreval("Digite a segunda nota:")
     leia(n2)
     media <- (n1 + n2)/2
     escreval("A média do aluno" , alunos, " é:", media)
     escreval()
fimpara


fimalgoritmo
