algoritmo "semnome"
// Função :
// Autor :
// Data : 25/04/2022
// Seção de Declarações 
var
QTDEMIN,QTDEMAX,estoquemedio:real


inicio
// Dados de Entrada
escreval("digite o valor da quantidade minima: ")
leia(QTDEMIN)
escreval("digite o valor da quantidade maxima: ")
leia(QTDEMAX)
// processamento
estoquemedio<-(QTDEMIN+QTDEMAX)/2
// Dados de Saída
escreval("O SEU ESTOQUE MEDIO É: ",estoquemedio)




fimalgoritmo
