algoritmo "semnome"
// Função :
// Autor :
// Data : 29/08/2022
// Seção de Declarações 
var
contador,termo,anterior,posterior,resultado:inteiro

inicio
escreval("digite um número para sequência de fibonacci")
leia(termo)

posterior<-1
para contador de 1 ate termo+1 faca
     resultado<-posterior+anterior
     escreval(resultado)
     posterior<-anterior
     anterior<-resultado

fimpara





fimalgoritmo
