algoritmo "semnome"
// Função :
// Autor :
// Data : 14/03/2022
// Seção de Declarações 
var
base:real
altura:real
area:real
inicio
// Seção de Comandos 
escreval("digite sua base: ")
leia(base)
escreval("digite sua altura: ")
leia(altura)
escreval(area)

escreval("a sua base é: ",base)
escreval("a sua altura é: ",altura)


area<-( (base*altura) / 2)

escreval("a area é de :",area)


fimalgoritmo
