algoritmo "semnome"
// Função :
// Autor :
// Data : 09/08/2022
// Seção de Declarações 
var
menor,maior,igual,salario:real
inicio
escreval("Digite o seu salário: ")
leia(salario)


se (salario<=1500) entao
   escreval("Você terá um aumento de 20%")
fimse
   se ((salario>1500) e (salario<=3000)) entao
      escreval("Você terá um aumento de 15%")
   fimse
      se (salario>3000) entao
         escreval("Você terá um aumento de 10%")
      fimse






fimalgoritmo
